shortener/urls.py
from django.urls import path

from . import views

app_name = 'shortener'
urlpatterns = [
    path('', views.index, name='index'),
    path('s/<url_id>', views.redirectUrl, name='redirectUrl'),
    path('view/', views.viewUrl, name='viewUrl'),
    path('view/<url_id>', views.viewUrlInfo, name='viewUrlInfo'),
]

ushort/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shortener.urls')),
]

shortener/models.py
from django.db import models

# A shorten url
class Url(models.Model):
    url_id = models.CharField("The short url id", max_length=8)
    orig_url = models.TextField("Original url")
    created_at = models.DateTimeField("Created at")
    clicks = models.IntegerField(default=0)

shortener/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Url
import random
import string
from django.utils import timezone
import re
from django.conf import settings

# Generate a random string
def random_string(length=8, chars=string.ascii_letters + string.digits):
    return ''.join([random.choice(chars) for x in range(length)])

# Short a url
def short_url(url_to_short):
    # Check if url already exists
    url_id = random_string(8)
    stop = False
    while not stop:
        # Are there any urls
        if not Url.objects.all():
            stop = True

        # Loop over every Url and then check it
        # TODO: Use filter
        for x in Url.objects.all():
            if x.url_id == url_id:
                url_id = random_string(8)
            else:
                stop = True

    # Add url ot database
    shorten_url = Url(url_id=random_string(8), orig_url=url_to_short, created_at=timezone.now())
    shorten_url.save()

    # Return the shorten url
    return shorten_url

def is_url(str):
    # Valid regexes
    url_regex = re.compile(
        r'^(?:http|ftp)s?://'
        r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?)|'
        r'localhost|'
        r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
        r'(?::\d+)?'
        r'(?:/?|[/?]\S+)$', re.IGNORECASE)

    # Return if str matches
    return re.match(url_regex, str) is not None

# Index page
def index(request):
    # Check if a url was sent through a post request
    error = None
    success = None
    if request.method == "POST" and request.POST["url"]:
        url_to_short = request.POST["url"]
        # Check if url_to_short is a valid url
        # TODO: Fix error: If url is empty, no result is printed out
        if not is_url(url_to_short) or url_to_short.strip() == "":
            error = "The entered url is invalid!"
        else:
            shorten_url = short_url(url_to_short)
            success = {
                "orig_url": shorten_url.orig_url,
                "short_url": settings.SERVER_URL + reverse("shortener:redirectUrl", args=[shorten_url.url_id])
            }

    return render(request, "shortener/index.html", {
        "error": error,
        "success": success
    })

# Redirect a user to an url
def redirectUrl(request, url_id):
    # Get the url
    url = get_object_or_404(Url, url_id=url_id)

    # Add 1 to clicks
    url.clicks += 1
    url.save()

    # Redirect
    return redirect(url.orig_url)

# Render the textbox to enter the url_id
def viewUrl(request):
    # Render
    return render(request, "shortener/viewUrl.html", {
        "url_scheme": settings.SERVER_URL + reverse("shortener:redirectUrl", args=["THIS_IS_THE_PART_WHICH_IS_CALLED_THE_URL_ID"]),
        "url_scheme_example": settings.SERVER_URL + reverse("shortener:redirectUrl", args=["abcdefgh"]),
        "base_url": settings.SERVER_URL
    })

# Show url information
def viewUrlInfo(request, url_id):
    # Get the url
    url = get_object_or_404(Url, url_id=url_id)

    # Render the url info page
    return render(request, "shortener/viewUrlInfo.html", {
        "url": url,
        "base_url": settings.SERVER_URL
    })

shortener/templates/shortener/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Some required meta stuff -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>ushort - {% block title %}{% endblock %}</title>

    <!-- Stylesheet(s) -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/shortener/style.css">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg nav-light-theme">
        <a class="navbar-brand" href="{% url 'shortener:index' %}">ushort</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav mr-auto">
                <!-- Link: Index -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shortener:index' %}"><i class="fa fa-home"></i> Home</a>
                </li>
                <!-- Link: View url informations -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shortener:viewUrl' %}"><i class="fa fa-eye"></i> View</a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- Content -->
    {% block content %}
    {% endblock %}

    <!-- JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    {% block js %}
    {% endblock %}
</body>
</html>

shortener/templates/shortener/index.html
{% extends 'shortener/base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-md-1 cont-dark">
                <h3  style="padding-top: 5px;" align="center">Short an url</h3>
                {% if error %}
                    <p><span class="text-error">Error!</span> {{ error }}</p>
                {% endif %}
                {% if success %}
                    <p><span class="text-success">Success!</span> The shorten url for <a href="{{ success.orig_url }}">{{ success.orig_url }}</a> is <a href="{{ success.short_url }}">{{ success.short_url }}</a></p>
                {% endif %}
                <form style="padding-bottom: 10px;" action="{% url 'shortener:index' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="url">Url</label>
                        <input type="url" class="form-control form-text-field" id="url" name="url" placeholder="Url">
                    </div>
                    <button type="submit" class="btn btn-blue">Short</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

shortener/templates/shortener/viewUrl.html
{% extends 'shortener/base.html' %}
{% block title %}View{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-md-1 cont-dark">
                <h3  style="padding-top: 5px;" align="center">View information about a shorten url</h3>
                <p style="display: none;" id="error"><span class="text-error">Error!</span> <span id="errorMsg"></span></p>
                <div style="padding-bottom: 10px;">
                    <div class="form-group">
                        <label for="urlId">Url (ID) <a href="#" data-toggle="modal" data-target="#urlIdInfo">(?)</a></label>
                        <input type="text" class="form-control form-text-field" id="urlId" placeholder="Url (ID)">
                    </div>
                    <button id="viewbutton" class="btn btn-blue">View</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal: Url ID -->
    <div class="modal fade" id="urlIdInfo" tabindex="-1" role="dialog" aria-labelledby="urlIdInfoLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="urlIdInfoLabel">What is an "Url ID"?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h6><b>What is this?</b></h6>
                    <p>We use the so called "Url ID" internally to identify the shorten urls. We store them along with the original url in our database.</p>
                    <h6><b>How to get it?</b></h6>
                    <p>That's fairly simple. It's the part behind a specific part behind the url. The scheme of the url is the following: {{ url_scheme }}. For example: In the url {{ url_scheme_example }} the url id is abcdefgh.</p>
                    <h6><b>Do i really need this?</b></h6>
                    <p>No. You can enter the whole url and we'll parse it for you. Use it if you want but you don't need to :)</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $("#viewbutton").click(function() {
            // View button was clicked
            // Content of #urlId
            var urlId = $("#urlId").val();

            // Check if theres an url id in there and get the url id
            if(urlId.startsWith("{{ base_url }}" + "{% url 'shortener:redirectUrl' 'REPLACE_THIS_WITH_NOTHING' %}".replace("REPLACE_THIS_WITH_NOTHING", ""))) {
                urlId = urlId.split("{% url 'shortener:redirectUrl' 'REPLACE_THIS_WITH_NOTHING' %}".replace("REPLACE_THIS_WITH_NOTHING", ""))[1];
            } else if(!(urlId.length == 8)) {
                $("#errorMsg").text("The code doesn't have the correct length.");
                $("#error").show();
                return;
            }

            // Url id is accessible here => Redirect
            window.location.href = "{{ base_url }}" + "{% url 'shortener:viewUrlInfo' 'REPLACE_THIS_WITH_URL_ID' %}".replace("REPLACE_THIS_WITH_URL_ID", urlId);
        });
    </script>
{% endblock %}

shortener/templates/shortener/viewUrlInfo.html
{% extends 'shortener/base.html' %}
{% block title %}View :: {{ url.url_id }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-md-1 cont-dark">
                <h3  style="padding-top: 5px;" align="center">View information about shorten url {{ url.url_id }}</h3>
                <div style="padding-bottom: 10px;">
                    <p>
                        <b>Url ID:</b> {{ url.url_id }}<br>
                        <b>Short url:</b> <a href="{{ base_url }}{% url 'shortener:redirectUrl' url.url_id %}">{{ base_url }}{% url 'shortener:redirectUrl' url.url_id %}</a><br>
                        <b>Original url:</b> <a href="{{ url.orig_url }}">{{ url.orig_url }}</a><br>
                        <b>Clicks:</b> {{ url.clicks }}<br>
                        <b>Created at:</b> {{ url.created_at }}<br>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}